/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class FrameResto extends javax.swing.JFrame {

    /**
     * Creates new form FrameResto
     */
    public FrameResto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox3 = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lalapanikan = new javax.swing.JCheckBox();
        lalapanayam = new javax.swing.JCheckBox();
        ayamkrispy = new javax.swing.JCheckBox();
        ayambakar = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        hargaikan = new javax.swing.JTextField();
        hargaayam = new javax.swing.JTextField();
        hargaayamkrispy = new javax.swing.JTextField();
        hargaayambakar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        jumlahikan = new javax.swing.JTextField();
        jumlahayam = new javax.swing.JTextField();
        jumlahayamkrispy = new javax.swing.JTextField();
        jumlahayambakar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        totalikan = new javax.swing.JTextField();
        totalayam = new javax.swing.JTextField();
        totalayamkrispy = new javax.swing.JTextField();
        totalayambakar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totalfull = new javax.swing.JTextField();
        diskon = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();

        jCheckBox3.setText("jCheckBox3");

        jTextField2.setText("jTextField2");

        jTextField5.setText("jTextField5");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 204));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel1.setText("Aplikasi Restoran");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel2.setText("Menu Makanan");

        lalapanikan.setText("Lalap Ikan");
        lalapanikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lalapanikanActionPerformed(evt);
            }
        });

        lalapanayam.setText("Lalapan Ayam");
        lalapanayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lalapanayamActionPerformed(evt);
            }
        });

        ayamkrispy.setText("Ayam Krispy");
        ayamkrispy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayamkrispyActionPerformed(evt);
            }
        });

        ayambakar.setText("Ayam Bakar");
        ayambakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayambakarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel3.setText("Harga");

        hargaikan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaikan.setText("0");
        hargaikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaikanActionPerformed(evt);
            }
        });

        hargaayam.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaayam.setText("0");

        hargaayamkrispy.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaayamkrispy.setText("0");

        hargaayambakar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaayambakar.setText("0");

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel4.setText("Jumlah");

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        jumlahikan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahikan.setText("0");

        jumlahayam.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahayam.setText("0");

        jumlahayamkrispy.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahayamkrispy.setText("0");

        jumlahayambakar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahayambakar.setText("0");

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel5.setText("Sub Total");

        totalikan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalikan.setText("0");
        totalikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalikanActionPerformed(evt);
            }
        });

        totalayam.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalayam.setText("0");

        totalayamkrispy.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalayamkrispy.setText("0");
        totalayamkrispy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalayamkrispyActionPerformed(evt);
            }
        });

        totalayambakar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalayambakar.setText("0");
        totalayambakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalayambakarActionPerformed(evt);
            }
        });

        jLabel6.setText("Total");

        jLabel8.setText("Diskon");

        jLabel9.setText("Total Bayar");

        totalfull.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalfull.setText("0");

        diskon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        diskon.setText("0");

        bayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        bayar.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(lalapanikan)
                                    .addComponent(lalapanayam)
                                    .addComponent(ayamkrispy)
                                    .addComponent(ayambakar))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(hargaayambakar, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(hargaayamkrispy)
                                    .addComponent(hargaayam)
                                    .addComponent(hargaikan)))
                            .addComponent(hitung))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jumlahayam, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(jumlahikan))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(totalikan))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(totalayam, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jumlahayamkrispy, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                        .addComponent(jumlahayambakar))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(totalayambakar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalayamkrispy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(totalfull)
                                    .addComponent(diskon)
                                    .addComponent(bayar)))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lalapanikan)
                        .addComponent(hargaikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jumlahikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lalapanayam)
                    .addComponent(hargaayam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahayam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalayam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ayamkrispy)
                    .addComponent(hargaayamkrispy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahayamkrispy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalayamkrispy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ayambakar)
                    .addComponent(hargaayambakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahayambakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalayambakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hitung)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(totalfull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(diskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hargaikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaikanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaikanActionPerformed

    private void totalayambakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalayambakarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalayambakarActionPerformed

    private void totalikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalikanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalikanActionPerformed

    private void totalayamkrispyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalayamkrispyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalayamkrispyActionPerformed

    private void lalapanikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lalapanikanActionPerformed
        // Kode untuk cekboks lalapan ikan
        if (lalapanikan.isSelected()){
            hargaikan.setEnabled(true);
            jumlahikan.setEnabled(true);           
            totalikan.setEnabled(true);
        }else{
            hargaikan.setEnabled(false);
            jumlahikan.setEnabled(false);
            totalikan.setEnabled(false);
        }

    }//GEN-LAST:event_lalapanikanActionPerformed

    private void lalapanayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lalapanayamActionPerformed
       // Kode untuk lalapan ayam
        if (lalapanayam.isSelected()){
            hargaayam.setEnabled(true);
            jumlahayam.setEnabled(true);           
            totalayam.setEnabled(true);
        }else{
            hargaayam.setEnabled(false);
            jumlahayam.setEnabled(false);
            totalayam.setEnabled(false);
        }

    }//GEN-LAST:event_lalapanayamActionPerformed

    private void ayamkrispyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayamkrispyActionPerformed
        // Kode untuk cekbox ayam krispi
        if (ayamkrispy.isSelected()){
            hargaayamkrispy.setEnabled(true);
            jumlahayamkrispy.setEnabled(true);
            totalayamkrispy.setEnabled(true);
        }else{
            hargaayamkrispy.setEnabled(false);
            jumlahayamkrispy.setEnabled(false);
            totalayamkrispy.setEnabled(false);
        }

    }//GEN-LAST:event_ayamkrispyActionPerformed

    private void ayambakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayambakarActionPerformed
        // Kode untuk cekbox ayam bakar
        if (ayambakar.isSelected()){
            hargaayambakar.setEnabled(true);
            jumlahayambakar.setEnabled(true);           
            totalayambakar.setEnabled(true);
        }else{
            hargaayambakar.setEnabled(false);
            jumlahayambakar.setEnabled(false);
            totalayambakar.setEnabled(false);
        }

    }//GEN-LAST:event_ayambakarActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // Kodingan untuk tombol button
        int harga = Integer.parseInt(hargaikan.getText());
        int jumlah = Integer.parseInt(jumlahikan.getText());
        totalikan.setText(Integer.toString(jumlah * harga)); //Menghitung subTotal harga ikan
        
        int harga1 = Integer.parseInt(hargaayam.getText());
        int jumlah1= Integer.parseInt(jumlahayam.getText());
        totalayam.setText(Integer.toString(harga1 * jumlah1));//menghitung subTotal harga ayam
        
        int harga2 = Integer.parseInt(hargaayamkrispy.getText());
        int jumlah2 = Integer.parseInt(jumlahayamkrispy.getText());
        totalayamkrispy.setText(Integer.toString(harga2 * jumlah2)); //Menghitung subTotal harga ayam krispi
        
        int harga3 = Integer.parseInt(hargaayambakar.getText());
        int jumlah3 = Integer.parseInt(jumlahayambakar.getText());
        totalayambakar.setText(Integer.toString(harga3 * jumlah3)); //Menghitung subTotal harga ayam bakar
        
        // Menghitung harga total, diskon dan total bayar
        int Total1 = Integer.parseInt(totalikan.getText());
        int Total2 = Integer.parseInt(totalayam.getText());
        int Total3 = Integer.parseInt(totalayamkrispy.getText());
        int Total4 = Integer.parseInt(totalayambakar.getText());
        int Full = Total1 + Total2 + Total3 + Total4;
        totalfull.setText("Rp." + Full + ",00");
        if (Full > 250000){
            diskon.setText("20%");
            Full = Full-(Full * 20/100);
            bayar.setText("Rp." + Full + ",00");
        }else if (Full > 150000){
            diskon.setText("10%");
            Full = Full-(Full*10/100);
            bayar.setText("Rp." + Full + ",00");
        }else{
            bayar.setText("Rp."+Full+",00");
        }

    }//GEN-LAST:event_hitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameResto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameResto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameResto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameResto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameResto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ayambakar;
    private javax.swing.JCheckBox ayamkrispy;
    private javax.swing.JTextField bayar;
    private javax.swing.JTextField diskon;
    private javax.swing.JTextField hargaayam;
    private javax.swing.JTextField hargaayambakar;
    private javax.swing.JTextField hargaayamkrispy;
    private javax.swing.JTextField hargaikan;
    private javax.swing.JButton hitung;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jumlahayam;
    private javax.swing.JTextField jumlahayambakar;
    private javax.swing.JTextField jumlahayamkrispy;
    private javax.swing.JTextField jumlahikan;
    private javax.swing.JCheckBox lalapanayam;
    private javax.swing.JCheckBox lalapanikan;
    private javax.swing.JTextField totalayam;
    private javax.swing.JTextField totalayambakar;
    private javax.swing.JTextField totalayamkrispy;
    private javax.swing.JTextField totalfull;
    private javax.swing.JTextField totalikan;
    // End of variables declaration//GEN-END:variables
}
